// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJynowjk0uj4IMiyLUz-B2aCk5wdRIGE',
    appId: '1:625937545028:android:20daeeb5c722645512c911',
    messagingSenderId: '625937545028',
    projectId: 'thunder-chat-app',
    storageBucket: 'thunder-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQENELE_hv0dY5vvxyvbN7oLvdz1Ign_g',
    appId: '1:625937545028:ios:45f39290462ad7ee12c911',
    messagingSenderId: '625937545028',
    projectId: 'thunder-chat-app',
    storageBucket: 'thunder-chat-app.appspot.com',
    iosClientId: '625937545028-05qpv8qdt18defteaqulepm3tp4h7lqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.thunderChatApp',
  );
}
